import type { Metadata } from "next";
import "./globals.css";
import SmoothScroller from "@/components/SmoothScroller";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "WebSite Demo 04",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="font-features-['palt'] h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroller>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </SmoothScroller>
      </body>
    </html>
  );
}
